### ISSUE TITLE
EndPoint to test 

### ISSUE THREAD

**Issue by suvarnaratna** [clover/remote-pay-ios#13]
Hi,

I am using Clover iOS SDK in my project to make payments.

I want to know what will be the endpoint url to connect to the external device.

Thank you,
Suvarna Ratna A

**Comment by cloverdaniel** [comment]
You'll need the Secure Network Pay Display app from the Clover App Market, which will host the server that you can connect to from your point-of-sale. From there, you'll connect to the following URL/endpoint: `wss://<ip_address>:12345/remote_pay`
